csharp1525
BorisDog/mongo-csharp-driver pull request #4
Opened 2021-01-05 20:43 UTC by BorisDog

2021-01-05 20:51 UTC, BorisDog commented on src/MongoDB.Bson/IO/JsonReader.cs
> +            }
Try to reset after reading a token (buffer will reset only if `MinResetBufferSize` chars read)

2021-01-05 20:52 UTC, BorisDog commented on src/MongoDB.Bson/IO/JsonReader.cs
> +            _bookmarks.Remove(jsonReaderBookmark);
Show we disallow custom created bookmarks (maybe as an `JsonReaderSettings` option)?

2021-01-11 16:26 UTC, rstam commented on src/MongoDB.Bson/IO/JsonReaderSettings.cs
> +
Can we use an approach that doesn't involve adding any new public APIs?

2021-01-13 19:15 UTC, BorisDog commented on src/MongoDB.Bson/IO/JsonReaderSettings.cs
> +
We can, but:
1. Would not it be beneficial to provide tuning options for advanced JsonReader.cs users?
2. Wanted to introduce "killswitch" with JsonReaderSettings.AutoBufferReset

2021-01-13 19:23 UTC, rstam commented on src/MongoDB.Bson/IO/JsonReaderSettings.cs
> +
We have a "no knobs" principle at MongoDB.

In practice that really means "as few knobs as possible".

2021-01-13 19:29 UTC, BorisDog commented on src/MongoDB.Bson/IO/JsonReaderSettings.cs
> +
I see, would want to leave JsonReaderSettings.AutoBufferReset if we were to proceed with this approach?

2021-01-13 19:31 UTC, rstam commented on src/MongoDB.Bson/IO/JsonReaderSettings.cs
> +
I haven't reviewed carefully besides pointing out that we would prefer not to change the public API at all if possible.

Can we find an approach that "just works" without requiring any public API changes?

2021-01-13 19:42 UTC, BorisDog commented on src/MongoDB.Bson/IO/JsonReaderSettings.cs
> +
Yes, the suggested change should just work. JsonReaderSettings.AutoBufferReset is proposed for additional safety. Whether we can do without it depends on our confidence of the proposed changes.

2021-02-02 20:12 UTC, DmitryLukyanov reviewed
Initial review. I will take a look at the changes itself after Robert

2021-02-02 20:12 UTC, DmitryLukyanov commented on src/MongoDB.Bson/IO/JsonBuffer.cs
> +        /// <summary>Initializes a new instance of the <see cref="JsonBuffer" /> class.</summary>
let's use the default formatting for xml comment:

    /// <summary>
    /// ...
    /// </summary>

2021-02-02 20:12 UTC, DmitryLukyanov commented on src/MongoDB.Bson/IO/JsonBuffer.cs
> +        /// <param name="readChunkSize"></param>
missed params

2021-02-02 20:12 UTC, DmitryLukyanov commented on src/MongoDB.Bson/IO/JsonReaderSettings.cs
> +        public bool AutoBufferReset { get; set; } = true;
in the current styling guide, we don't use auto properties

2021-02-02 20:12 UTC, DmitryLukyanov commented on src/MongoDB.Bson/IO/JsonReaderSettings.cs
> +        public bool AutoBufferReset { get; set; } = true;
Also, properties should be placed after constructor

2021-02-15 19:22 UTC, rstam requested changes

2021-02-15 19:22 UTC, rstam commented on src/MongoDB.Bson/IO/JsonReaderSettings.cs
> +
I think you should remove these new settings (knobs).

They are not required.

The ticket is about clearing the buffer when possible to reduce memory consumption, not about making more things configurable.

2021-02-15 19:22 UTC, rstam commented on src/MongoDB.Bson/IO/JsonReader.cs
> +            }
There is no requirement that `ReturnToBookmark` be called (it might or it might not).

Therefore, there is no guarantee that the `Count` will ever go back to zero.

I think we need a new approach.

2021-02-18 17:42 UTC, closed without merging